--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Ingres-Utility-Netutil
version:      0.03
version_from: lib/Ingres/Utility/Netutil.pm
installdirs:  site
requires:
    Carp:                          0
    Expect::Simple:                0
    Test::More:                    0

distribution_type: module
license:      perl
generated_by: ExtUtils::MakeMaker version 6.17
