# http://module-build.sourceforge.net/META-spec.html
name:         Ingres-Utility-Netutil
version:      0.02
version_from: lib/Ingres/Utility/Netutil.pm
abstract:     API to NETUTIL Ingres RDBMS utility
author:
              - Joner Cyrre Worm <FAJCNLXLLXIH at spammotel.com>
license:      perl
installdirs:  site
requires:
              Expect::Simple:                0
              Test::More:                    0
distribution_type: module
resources:
              homepage: http://www.joner.org
generated_by: ExtUtils::MakeMaker version 6.17
